<!DOCTYPE html>
<html>
<head>
    <title>Page Title</title>
</head>
<body>

    <h1>This is a Heading</h1>
    <p>This is a paragraph.</p>

</body>
<script>


    const promisone = new Promise(function (resolve, reject) {
        //Do an asynk task
        //DB calls, cryptography,network
        setTimeout(() => {
            console.log("Asynk task is compelete")
            resolve()///connect to then
        }, 1000);
    })

    promisone.then(() => {
        console.log("Promises Comsume");
    })

    new Promise(function (resolve, reject) {
        setTimeout(() => {
            console.log("Asynk task is compelete 2")
            resolve()///connect to then
        }, 1000);
    }).then(() => {
        console.log("Promises 2 resolve Comsume");
    })

    const Promisthree = new Promise(function (resolve, reject) {
        setTimeout(() => {
            console.log("Asynk task is compelete 2")
            resolve({ username: "kapoor", email: "kapoor@exmple.com" })///connect to then
        }, 1000);
    });

    Promisthree.then(function (user) {
        console.log(user);
    });

    const Promisfour = new Promise(function (resolve, reject) {
        setTimeout(() => {
            console.log("Asynk task is compelete 4")
            let error = false;
            if (!error) {
                resolve({ username: "kapoor", pass: "123" })///connect to then
            }
            else {
                reject('Error: Something went Wrong');
            }
        }, 1000);
    })
    Promisfour
        .then(function (user) {
            console.log(user);
            return user.username;
        })
        .then((username) => {
            console.log(username);
        })
        .catch((error) => {
            console.log(error);
        }).finally(() => {
            console.log("Promis finally Done");
        });

    const promisefive = new Promise(function (resolve, reject) {
        setTimeout(() => {
            console.log("Asynk task is compelete 5")
            let error = true;
            if (!error) {
                resolve({ username: "javascriot", pass: "123" })///connect to then
            }
            else {
                reject('Error: JS went Wrong');
            }
        }, 1000);
    });
    async function consumepromisefive() {
        try {
            const res = await promisefive
            console.log(res)
        }
        catch (error) {
            console.log(error)
        }
    }
    consumepromisefive()

    //async function getAllUsers() {
    //    try {
    //        const res = await fetch('https://jsonplaceholder.typicode.com/users')
           
    //        const data=await res.json();
    //        console.log(data)
    //    } catch (error) {
    //        console.log(error)
    //    }
    //}

    //getAllUsers()

    
    fetch('https://jsonplaceholder.typicode.com/users')
        .then((response) => {
            return response.json();
        })
        .then((res) => {
            console.log(res);
        })
        .catch((error) => {
            console.log(error)
        })






</script>
</html>
